#pragma config(Motor,  port1,           motorForward,  tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
		{
			int forwards = vexRT(Ch3);
			int deadzone = 5;

			if (forwards >= 10)
			{
				motor[motorForward] = forwards;
			}
			else if (forwards <= -10)
			{
				motor[motorForward] = forwards;
			}
			else
			{
				motor[motorForward] = 0;
			}
			if(vexRT[Btn8D]==1)
			{
				setServo(port2,127);
			}
			else if(vexRT[Btn7D]==1)
			{
				setServo(port2,-127);
			}
		}
}
